
define(['require'], function(require) {
    return {
        align: require('./align'),
        autosizecolumn: require('./autosizecolumn'),
        backdrop: require('./backdrop'),
        columnmoving: require('./columnmoving'),
        columnsizing: require('./columnsizing'),
        directinput: require('./directinput'),
        dragging: require('./dragging'),
        dummy: require('./dummy'),
        editing: require('./editing'),
        editing_currency: require('./editing_currency'),
        editing_date: require('./editing_date'),
        editing_number_int: require('./editing_number_int'),
        editing_option: require('./editing_option'),
        eventhandlers: require('./eventhandlers'),
        export_csv: require('./export_csv'),
        extensions: require('./extensions'),
        filtering: require('./filtering'),
        filtering_date: require('./filtering_date'),
        filtering_option: require('./filtering_option'),
        filtering_scalar: require('./filtering_scalar'),
        flexcolumns: require('./flexcolumns'),
        formatting: require('./formatting'),
        grouping: require('./grouping'),
        rowhighlighting: require('./rowhighlighting'),
        selection: require('./selection'),
        sorting: require('./sorting'),
        statistics: require('./statistics'),
        styling: require('./styling'),
        subcells: require('./subcells'),
        subgrids: require('./subgrids'),
        subview: require('./subview'),
        summarize: require('./summarize'),
        templating: require('./templating'),
        treegrid: require('./treegrid'),
        validation: require('./validation'),
        variablerowheight: require('./variablerowheight')
    };
});
